# Generated by Django 2.0.2 on 2018-03-02 13:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for this booking', max_length=50)),
                ('description', models.CharField(blank=True, help_text='Enter a description for this booking', max_length=300, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this calendar', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a name for this booking schedule', max_length=50)),
                ('google_calendar_id', models.CharField(help_text='Enter a calendar id', max_length=50)),
                ('username', models.CharField(help_text='Enter a calendar username', max_length=100)),
                ('password', models.CharField(help_text='Enter a calendar password', max_length=100)),
                ('timezone', models.CharField(choices=[('Europe/Stockholm', 'Europe/Stockholm')], default='Europe/Stockholm', help_text='Calendar timezone', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this bookinginstance', primary_key=True, serialize=False)),
                ('Google_Calendar_Booking_Id', models.CharField(blank=True, help_text='Unique ID from google after instance is created', max_length=300, null=True)),
                ('start', models.DateTimeField(help_text='Start of event')),
                ('end', models.DateTimeField(help_text='End of event')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.Booking')),
            ],
            options={
                'ordering': ['start', 'end'],
            },
        ),
        migrations.CreateModel(
            name='BookingTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for this template', max_length=50)),
                ('title', models.CharField(help_text='Enter title for booking', max_length=100)),
                ('header', models.CharField(blank=True, help_text='Enter a, optional, header for the booking to be inserted before the hosts name', max_length=200, null=True)),
                ('body', models.TextField(help_text='Enter a body for the booking', max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.BookingCalendar'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.BookingTemplate'),
        ),
    ]
