# Generated by Django 2.0.2 on 2018-03-07 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcalendar',
            name='scope',
            field=models.TextField(default='noscope', help_text='enter context of api calls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingcalendar',
            name='service_account',
            field=models.TextField(default='test', help_text='enter content of service.json'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinginstance',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Reschedule'), (0, 'Unscheduled'), (1, 'Scheduled'), (2, 'Cancelled')], default=0, help_text='Instance status'),
        ),
        migrations.AlterField(
            model_name='bookingcalendar',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this calendar', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookingcalendar',
            name='password',
            field=models.CharField(blank=True, help_text='Enter a calendar password', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookinginstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this bookinginstance', primary_key=True, serialize=False),
        ),
    ]
