# Generated by Django 2.0.5 on 2018-07-27 13:16

from django.db import migrations
from ..models import User

def create_testdata(apps, schema_editor):
    SchedulingCalendar = apps.get_model('scheduler', 'SchedulingCalendar')
    EventTemplate = apps.get_model('scheduler', 'EventTemplate')
    SchedulingRule = apps.get_model('scheduler', 'SchedulingRule')
    Event = apps.get_model('scheduler', 'Event')

    calendar = SchedulingCalendar.objects.create(name="Testkalender", google_calendar_id="1234", service_account_username="test", timezone="Europe/Stockholm")
    template = EventTemplate.objects.create(name="Template-Måndag", title="Makermåndag", synchronize=False, calendar=calendar)
    rule = SchedulingRule.objects.create(name="Varje måndag", description="Repeats every monday", frequency="WEEKLY", params="byweekday:MO")
    event = Event.objects.create(name="Måndagar", template=template, start="2018-05-27 13:00:00", end="2018-05-27 16:00:00", rule=rule)

def create_testusers(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.email = "admin"
    superuser.set_password('adminadmin')
    superuser.save()

    user1 = User()
    user1.is_active = True
    user1.is_superuser = False
    user1.is_staff = False
    user1.email = "user1"
    user1.set_password('testtest')
    user1.save()

    user2 = User()
    user2.is_active = True
    user2.is_superuser = False
    user2.is_staff = False
    user2.email = "user2"
    user2.set_password('testtest')
    user2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_testusers),
        migrations.RunPython(create_testdata)
    ]