# Generated by Django 2.0.2 on 2018-03-08 09:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20180307_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinginstance',
            old_name='Google_Calendar_Booking_Id',
            new_name='google_calendar_booking_id',
        ),
        migrations.RemoveField(
            model_name='bookingcalendar',
            name='password',
        ),
        migrations.RemoveField(
            model_name='bookingcalendar',
            name='username',
        ),
        migrations.AddField(
            model_name='booking',
            name='synchronize',
            field=models.BooleanField(default=True, help_text='If active, events will be synced to Google calendar'),
        ),
        migrations.AddField(
            model_name='bookingcalendar',
            name='service_account_username',
            field=models.CharField(default='nouser', help_text='Enter the username for the service account used', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinginstance',
            name='host',
            field=models.CharField(blank=True, help_text='Enter a name instead of user-key', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookingcalendar',
            name='google_calendar_id',
            field=models.CharField(help_text='Enter a calendar id', max_length=250),
        ),
        migrations.AlterField(
            model_name='bookingcalendar',
            name='scope',
            field=models.TextField(default='https://www.googleapis.com/auth/calendar', help_text='enter scope of api calls, change at your own risk'),
        ),
        migrations.AlterField(
            model_name='bookingcalendar',
            name='service_account',
            field=models.FileField(help_text='Upload client_secret json-file', storage=django.core.files.storage.FileSystemStorage(location='/home/bobo/django-apps/makerslink/pks'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookinginstance',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Reschedule needed'), (0, 'Unscheduled'), (1, 'Scheduled'), (2, 'Cancelled')], default=0, help_text='Instance status'),
        ),
        migrations.AlterField(
            model_name='bookingtemplate',
            name='body',
            field=models.TextField(blank=True, help_text='Enter a body for the booking to be inserted after the hosts name', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookingtemplate',
            name='header',
            field=models.CharField(blank=True, help_text='Enter a, optional, header for the booking to be inserted after the hosts name', max_length=200, null=True),
        ),
    ]
