# Generated by Django 2.0.2 on 2018-03-17 09:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20180308_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('frequency', models.CharField(choices=[('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('DAILY', 'Daily')], max_length=10, verbose_name='frequency')),
                ('params', models.TextField(blank=True, verbose_name='params')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_calendar',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='synchronize',
        ),
        migrations.AddField(
            model_name='booking',
            name='end',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 17, 10, 4, 6, 817196), help_text='End of event, must be after start'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='repeat_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 10, 4, 18, 458250), help_text='Day to end repetition (repetition excludes this date)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 17, 10, 4, 28, 731021), help_text='Start of event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingtemplate',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.BookingCalendar'),
        ),
        migrations.AddField(
            model_name='bookingtemplate',
            name='synchronize',
            field=models.BooleanField(default=True, help_text='If active, events will be synced to Google calendar'),
        ),
        migrations.AlterField(
            model_name='bookingcalendar',
            name='timezone',
            field=models.CharField(choices=[('Europe/Stockholm', 'Europe/Stockholm')], help_text='Calendar timezone', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='rule',
            field=models.ForeignKey(blank=True, help_text="Select '----' for a one time only event.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.SchedulingRule'),
        ),
    ]
