# Generated by Django 2.0.5 on 2018-08-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20180727_2104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventinstance',
            unique_together={('event', 'start', 'end')},
        ),
    ]
