# Generated by Django 2.0.2 on 2018-04-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20180317_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='repeat_end',
            field=models.DateTimeField(help_text='Day to end repetition'),
        ),
    ]
