# Generated by Django 2.0.5 on 2018-05-24 17:44

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20180412_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a human-friendly name for this type of Event', max_length=50)),
                ('description', models.CharField(blank=True, help_text='Enter a description for this type of Event', max_length=300, null=True)),
                ('start', models.DateTimeField(db_index=True, help_text='Start of event repetition and start time of events')),
                ('end', models.DateTimeField(db_index=True, help_text='End time of events, must be after start')),
                ('repeat_end', models.DateTimeField(help_text='Date to end repetition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this bookinginstance', primary_key=True, serialize=False)),
                ('google_calendar_booking_id', models.CharField(blank=True, help_text='Unique ID from google after instance is created', max_length=300, null=True)),
                ('host', models.CharField(blank=True, help_text='Enter a name instead of user-key', max_length=50, null=True)),
                ('start', models.DateTimeField(help_text='Start of event')),
                ('end', models.DateTimeField(help_text='End of event')),
                ('status', models.IntegerField(choices=[(-1, 'Reschedule needed'), (0, 'Unscheduled'), (1, 'Scheduled'), (2, 'Cancelled')], default=0, help_text='Instance status')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.Event')),
            ],
            options={
                'ordering': ['start', 'end'],
            },
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a human-friendly name for this template', max_length=50)),
                ('title', models.CharField(help_text='Enter title to be used for booking', max_length=100)),
                ('header', models.CharField(blank=True, help_text='Enter a, optional, header for the event to be inserted after the hosts name into the descriptionfield in the calendar event.', max_length=200, null=True)),
                ('body', models.TextField(blank=True, help_text='Enter a larger body of text to be inserted after the header in the description field in the calendar event', max_length=1000, null=True)),
                ('synchronize', models.BooleanField(default=True, help_text='If active, scheduled events will be synced to Google calendar upon creation.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchedulingCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this calendar', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a human-friendly name for this Google Calendar', max_length=50)),
                ('google_calendar_id', models.CharField(help_text='Enter a calendar id', max_length=250)),
                ('service_account_username', models.CharField(help_text='Enter the username for the service account used', max_length=250)),
                ('timezone', models.CharField(choices=[('Europe/Stockholm', 'Europe/Stockholm')], help_text='Calendar timezone', max_length=50)),
                ('service_account', models.FileField(help_text='Upload client_secret json-file', storage=django.core.files.storage.FileSystemStorage(location='/home/bobo/Documents/Projects/MakersLink-Scheduling/pks'), upload_to='')),
                ('scope', models.TextField(default='https://www.googleapis.com/auth/calendar', help_text='Enter scope of api calls, change at your own risk')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_template',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='bookinginstance',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingtemplate',
            name='calendar',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingCalendar',
        ),
        migrations.DeleteModel(
            name='BookingInstance',
        ),
        migrations.DeleteModel(
            name='BookingTemplate',
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='calendar',
            field=models.ForeignKey(help_text='Select the calendar to sync events to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.SchedulingCalendar'),
        ),
        migrations.AddField(
            model_name='event',
            name='booking_template',
            field=models.ForeignKey(help_text='Select a template for how scheduled Events will look in the calendar.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.EventTemplate'),
        ),
        migrations.AddField(
            model_name='event',
            name='rule',
            field=models.ForeignKey(blank=True, help_text="Select '----' for a one time only event.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.SchedulingRule'),
        ),
    ]
