# Generated by Django 2.0.5 on 2018-05-27 07:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20180524_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingcalendar',
            name='service_account',
            field=models.FileField(help_text='Upload client_secret json-file', null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/bobo/Documents/Projects/MakersLink-Scheduling/pks'), upload_to=''),
        ),
    ]
