# Generated by Django 2.0.5 on 2018-08-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_eventinstance_host'),
        ('scheduler', '0006_auto_20180801_1617'),
    ]

    operations = [
    ]
