# Generated by Django 2.0.5 on 2018-08-03 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0008_merge_20180803_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinstance',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
