# Generated by Django 2.0.5 on 2018-05-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20180527_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat_end',
            field=models.DateTimeField(blank=True, help_text='Date to end repetition', null=True),
        ),
    ]
