# Generated by Django 2.0.5 on 2018-06-03 09:02

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20180527_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booking_template',
            field=models.ForeignKey(help_text='Select a template for how scheduled Events will look in the calendar.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.EventTemplate', verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='schedulingcalendar',
            name='service_account',
            field=models.FileField(blank=True, help_text='Upload client_secret json-file', null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/larlin/Projects/MakersLink_Scheduling/pks'), upload_to=''),
        ),
    ]
