# Generated by Django 2.0.5 on 2018-06-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20180603_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='booking_template',
        ),
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.ForeignKey(help_text='Select a template for how scheduled Events will look in the calendar.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.EventTemplate'),
        ),
    ]
