# Generated by Django 2.0.5 on 2018-10-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20180828_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Start of period')),
                ('end', models.DateTimeField(help_text='End of period')),
            ],
        ),
    ]
