# Generated by Django 2.0.5 on 2018-10-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_schedulingperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingperiod',
            name='end',
            field=models.DateTimeField(db_index=True, help_text='End of period'),
        ),
        migrations.AlterField(
            model_name='schedulingperiod',
            name='start',
            field=models.DateTimeField(db_index=True, help_text='Start of period'),
        ),
    ]
