# Generated by Django 2.0.5 on 2018-10-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_auto_20181013_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingperiod',
            name='end',
            field=models.DateField(db_index=True, help_text='End of period'),
        ),
        migrations.AlterField(
            model_name='schedulingperiod',
            name='start',
            field=models.DateField(db_index=True, help_text='Start of period'),
        ),
    ]
