# Generated by Django 2.0.5 on 2018-10-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_auto_20181013_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinstance',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.SchedulingPeriod'),
        ),
    ]
