# Generated by Django 2.0.5 on 2018-10-18 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_eventinstance_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
