# Generated by Django 2.0.5 on 2018-10-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_auto_20181018_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.SchedulingPeriod'),
        ),
    ]
