# Generated by Django 2.0.5 on 2018-10-22 08:35

from django.db import migrations, models
import scheduler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_eventtemplate_count_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingperiod',
            name='num_required_events',
            field=models.IntegerField(default=6, help_text='Number of events a host should have in this period'),
        ),
        migrations.AddField(
            model_name='schedulingperiod',
            name='participant_key_string',
            field=scheduler.fields.ParticipantKeyField(default='', help_text='A string representing the events a host is required to be a participant to in this period', max_length=10),
        ),
    ]
