# Generated by Django 2.0.5 on 2019-04-14 13:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_auto_20181022_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingRuleExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_date', models.DateField(db_index=True, help_text='Date to exclude')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='schedulingrule',
            name='use_exclusions',
            field=models.BooleanField(default=True, help_text='If active, this rule for generating dates will ignore excluded dates generated dates falling on those dates will not be added.'),
        ),
        migrations.AlterField(
            model_name='schedulingcalendar',
            name='service_account',
            field=models.FileField(blank=True, help_text='Upload client_secret json-file', null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/bobo/PycharmProjects/scheduler/pks'), upload_to=''),
        ),
    ]
