# Generated by Django 3.0.7 on 2020-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_auto_20190417_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulingruleexclusion',
            options={'ordering': ['excluded_date']},
        ),
        migrations.AddField(
            model_name='eventinstance',
            name='unique_description',
            field=models.CharField(blank=True, default='', help_text='Enter a description for a cancelled event, leave blank to use default: Detta pass har blivit inställt, Makerspace Linköping har EJ öppet denna tid!', max_length=400),
        ),
        migrations.AddField(
            model_name='eventinstance',
            name='unique_title',
            field=models.CharField(blank=True, default='', help_text='Enter title to be inserted before the header when cancelling, leave blank to use default: Inställt: ', max_length=100),
        ),
    ]
