# Generated by Django 3.0.7 on 2020-06-15 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0024_auto_20200614_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingperiod',
            name='hosts',
            field=models.ManyToManyField(related_name='periods', related_query_name='period', to=settings.AUTH_USER_MODEL),
        ),
    ]
