# Generated by Django 3.0.7 on 2020-06-21 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0025_schedulingperiod_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', related_query_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
