# Generated by Django 3.0.7 on 2020-06-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0027_auto_20200621_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulingperiod',
            options={'ordering': ('-start', '-end')},
        ),
    ]
