# Generated by Django 3.1.14 on 2021-12-22 09:50

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0028_auto_20200626_1714'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(start__lt=django.db.models.expressions.F('end')), name='check_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(start__lt=django.db.models.expressions.F('repeat_end')), name='check_start_before_repeat_end'),
        ),
    ]
