# Generated by Django 2.0.5 on 2018-08-01 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180727_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slackId',
            field=models.CharField(max_length=21, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-z.\\-_]*$', 'Please enter a valid slackId.', code='invalid_slackId')]),
        ),
    ]
