# Generated by Django 2.0.5 on 2018-08-01 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180801_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slackId',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^((?!@).)*$', 'Please enter a slack name without @.', code='invalid_slackId')]),
        ),
    ]
