# Generated by Django 2.0.5 on 2018-08-16 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180807_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slackId',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^((?!@).)*$', 'Ange ditt slacknamn utan @-tecken.', code='invalid_slackId')], verbose_name='Slacknamn'),
        ),
    ]
